# services:
#   - type: web
#     name: document-research-chatbot
#     env: python
#     plan: free
#     buildCommand: |
#       pip install -r backend/requirements.txt
#       cd frontend
#       npm install
#       npm run build
#       cd ..
#       mkdir -p backend/build
#       cp -r frontend/build/* backend/build/
#     startCommand: python backend/run.py
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.10.11

services:
  - type: web
    name: document-research-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
