services:
  - type: web
    name: document-research-chatbot
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/build
      cp -r frontend/build/* backend/build/
    startCommand: python backend/run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
